### ISSUE TITLE
Evaluate information from HTTP monitoring

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#100]
We do HTTP monitoring for about 1 week now. I received 414 notification emails, I estimate this are 207 error reports. It seems most of these information are endpoints going down and then coming back shortly. This happens mostly with SPARQL endpoints.

Please write a list and check how many reports we receive for which check in a certain period. Starting time of this period should be the time when all tests were configured, I think this is the Nov 25. End time of the period should be the day you start this task.

The next step is to identify the most unreliable SPARQL endpoints / external services and see if we have to take any actions because of unreliability.

**Comment by m1ci** [comment]
Just a tip: the request go through the Broker so this might be an issue with the Broker and not with the SPARQL endpoint itself. This needs to be considered too.

**Comment by jnehring** [comment]
We setup monitoring of the SPARQL endpoints also. E.g. we monitor if http://dbpedia.org/sparql is available.

**Comment by m1ci** [comment]
there is LODStats tool for monitoring sparql endpoints and much more
- see http://aksw.org/Projects/LODStats.html

**Comment by jnehring** [comment]
Please add SLA stats (IT-Services tab) also for the external services in zabbix.

**Comment by ArneBinder** [comment]
Added SLA for external.

**Comment by jnehring** [comment]
Updated task description: Calculate statistics for december 2015:

* How many problem reports per check
* Total downtime
* Average downtime per problem

**Comment by ArneBinder** [comment]
done. 
see google drive folder: freme-project/Development/downtime stats
to re-generate the output use the query in freme_downtime_stats.sql

**Comment by jnehring** [comment]
All files in [GoogleDrive](https://drive.google.com/drive/folders/0B0tkh6Bg_AK5dmdsUUt0U3h5RlE).

**Comment by andish** [comment]
From report:

FREME 0.4: Check E-TRANSLATION failed --> 1 fail
TILDE: Check E-TRANSLATION failed -->25 fails

Why is such difference? FREME e-Translation service depends on Tilde service.

**Comment by jnehring** [comment]
We have our report setup in a way that a fail of FREME e-translation is only reported when the tilde translation check has not failed. In that way we can distinguish from problems within Tilde and problems within FREME in the monitoring.

**Comment by andish** [comment]
Ok, it is clear now. Is it possible get out from logs when Tilde services were down?

**Comment by andish** [comment]
Thanks to Jan for info
