### ISSUE TITLE
FREME services version numbers

### ISSUE THREAD

**Issue by ghsnd** [freme-project/technical-discussion#102]
At this moment, not all services that are part of FREME have the same version number. For instance, most services will have 0.5 for the next release, while e-Internationalization and pipelining will have version 0.3 because they started later.

Although *technically* speaking not correct, wouldn't it be more consistent and clear if all services would have the same version number at all times? So that every service in FREME version 0.5 has version 0.5?

**Comment by pheyvaer** [comment]
+1 because now it is hard to tell whether I'm using an old version or that the service is just newer.

**Comment by jnehring** [comment]
When you want to know if you included the latest version number you can look at 

http://rv1443.1blu.de/nexus/content/repositories/releases/eu/freme/

I can see that it might be confusing to have different version numbers, but enforcing all version numbers to be even more confusing also. We would have to at first update some artifacts like e-Internationalisation, so some version numbers would be skipped. Even worse is that if an artifact did not change during a release we would have to release it.

So I would not enforce equal version numbers across all artifacts just to avoid looking at the repository to check if there is a new version.
