### ISSUE TITLE
[NIF prov] tool which produced the annotation

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#104]

**Comment by neradis** [comment]
A reference to the tool that created an annotation is added either by the generic `nif:provenance` property or by a *property companion property*. In both cases the range is a union on `nif:Agent` and `nif:Activity`. Thus, a description of the tool used can be attatched directly, if no additional information on the annotation activity needs to be expressed (see https://github.com/freme-project/technical-discussion/blob/master/samples/nif21-agent-prov-comp-props.ttl and https://github.com/freme-project/technical-discussion/blob/master/samples/nif21-agent-prov-gen-props.ttl for examples:
```turtle
@prefix ex-api: <http://api.freme-project.eu/example/description/e-entity/Fdbpedia-spotlight/documents/> .

#[...] 

ex:doc_offset_0_5
  #[...] 
 itsrdf:taIdentRef dbp:Apple_Inc ;
  nif:taIdentConf "0.8"^^xsd:decimal ;
  nif:taIdentProv ex-api:v0.5 ;
  # [...]
```


 Some stub-like description for e-Entity as `nif:Agent` and the related FREME project can be found in https://github.com/freme-project/technical-discussion/blob/master/samples/freme-descriptions.ttl):
```turtle
ex-api:v0.5
  a prov:SoftwareAgent, doap:Version ;
  doap:shortdesc "NIF REST API for entity recognition and linking us  ing DBPedia Spotlight engine" ;
  doap:revision "0.5" ;
  dcterms:isPartOf <http://freme-project.eu/example/description/e-entity> .
#[...]
```
Alternatively provenance is described by a `prov:Activity` instance, which in turn specifies the tool involved in creating the annotation (see [issue on enocding annotation time](https://github.com/freme-project/technical-discussion/issues/105)
```

**Comment by jnehring** [comment]
this is implemented
