### ISSUE TITLE
[NIF prov] time when the annotation was generated

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#105]

**Comment by ghsnd** [comment]
I don't know if this is relevant, but if we include start and end timestamps, we can get an idea of the performance (modeled as prov, see also <http://www.w3.org/TR/2013/REC-prov-o-20130430/#startedAtTime>). But this might be more relevant on the service itself, not the annotation, see also freme-project/pipelines#14...

**Comment by neradis** [comment]
The time in which an annotation was added is either attached by the generic `nif:provenance` property or by a *provenance companion property* pointing to a `prov:Activity`. This activity resource can denote the start time for the annotation process (via `prov:startedAtTime`) and should denote the time the annotation was finished via `prov:endedAtTime`. Also, the activity resource should specifiy the FREME service used with `prov:wasAssociatedWith`:
```turtle
ex:doc_offset_0_5
  #[...]
  nif:anchorOf "Apple"^^xsd:string ;
  itsrdf:taIdentRef dbp:Apple_Inc ;
  nif:taIdentConf "0.8"^^xsd:decimal ;
  nif:taIdentProv _:act_1 ;

_:act_1 a prov:Activity ;
  prov:startedAtTime "2015-12-22T11:02:27.02Z"^^xsd:dateTime;
  prov:endedAtTime "2015-12-22T11:02:28.32Z"^^xsd:dateTime;
  prov:wasAssociatedWith ex-api:v0.5 .
```

On `ex-api:v0.5` see https://github.com/freme-project/technical-discussion/blob/master/samples/freme-descriptions.ttl and some comment in the [issue on tooling provenance](https://github.com/freme-project/technical-discussion/issues/104)

**Consideration:** One could also consider introducing a more specific sub-property of `prov:wasAssociatedWith`, e.g. called `freme:usedService` to specify which FREME service
was used. A benefit would be that the webservice used is identified more easily when additional Agents are also associated to the `nif:Activity`-resource.

**Comment by jnehring** [comment]
this discussion is over.
