### ISSUE TITLE
Try out tbx2rdf 

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#109]
Please try out how the TBX2RDF converter works. Some links
- https://github.com/cimiano/tbx2rdf
- http://www.w3.org/2015/09/bpmlod-reports/multilingual-terminologies/
- http://tbx2rdf.lider-project.eu/converter/index.html
- http://tbx2rdf.lider-project.eu/converter/doc/index.html

The goal of this task is to find out if the converter is stable enough to be integrated in FREME.

I think the online converter does not work right now.

Please create a collection of e.g. 5 TBX files and try to convert it to RDF. Store these RDF files so @andish can evaluate if the conversion is fine. Also create a list of TBX files that could not be converted using the tool.

**Comment by m1ci** [comment]
side note: if you have any questions, or found some issues feel free to open issue https://github.com/cimiano/tbx2rdf

**Comment by jnehring** [comment]
@ArneBinder please postpone this issue and do not work on it right now. I have another task for you.
