### ISSUE TITLE
LDF parameter in /e-link/explore

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#112]
The service /e-link/explore accepts endpoint type "sparql" and "ldf". Following [this argumentation](https://github.com/LinkedDataFragments/Server.js/issues/20) the endpoint type is not "ldf" but "tpf".

@pheyvaer do you use /e-link/explore in the CKEditor plugin? Does this change affect your codes?

When we do this we need to update this in
- Source code, probably e-link
- API documentation

**Comment by pheyvaer** [comment]
@bjdmees is this applicable to the plugin?

**Comment by m1ci** [comment]
@jnehring you are right, probably `tpf` should be the value for the triple fragments endpoints, and `sparql` for the SPARQL endpoints.

**Comment by jnehring** [comment]
this will not be changed.
