### ISSUE TITLE
outformat=text

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#113]
The [NIF API specifications](http://persistence.uni-leipzig.org/nlp2rdf/specification/api.html) say that "text" is a valid value for parameter outformat. This outputs the text in the "isString" properties in all contexts. We need to support this parameter value in order to be compliant with the NIF API specifications.

@m1ci do you think we need this feature? I cannot imagine a case when this is useful. Also the specification is vague on how to implement it - should multiple strings be separated by newlines?

The question was first asked by @PeterBourgonje

**Comment by m1ci** [comment]
I think we dont need.

**Comment by jnehring** [comment]
Ok so we can close this issue.
