### ISSUE TITLE
Unclear authentication

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#114]
In https://github.com/freme-project/e-Link/issues/67 @m1ci reported

> However, I think its not clear for a user how to authenticate. The message says:

> Could not create resource: The anonymous user can not own any resource. You have to be logged in to create a resource.

> 1) users do not log in
> 2) no clear info on how they should log in -> provide info that they should get token and provide it in the input field at the end of the page
> 3) the input field for the token is hard to find. I would rather add token input field next to every API resources where authentication is needed.

**Comment by jnehring** [comment]
1) Correct, we can change the error message to "Could not create resource: The anonymous user can not own any resource. You have to be authenticated to create a resource."
2+3) I propose a more simple solution: At every API call that requires authentication we provide some information in the description of the API call.

**Comment by m1ci** [comment]
> 2+3) I propose a more simple solution: At every API call that requires authentication we provide some information in the description of the API call.

What kind of description?

**Comment by jnehring** [comment]
I suggest

This api method requires user authentication. More information about this topic can be found in the [knowledge base article about authentication](http://api-dev.freme-project.eu/doc/knowledge-base/authentication.html). You can attach an API token to this request from this API tester using the "access token" input field on the bottom of this page.

**Comment by jnehring** [comment]
@bgrusdt please add this sentence to every api call in the full and simple api documentaiton that requires authentication.

**Comment by bgrusdt** [comment]
I added the sentence that Jan suggested. Can this issue be closed ?

**Comment by jnehring** [comment]
Thank you!
