### ISSUE TITLE
Evaluate piwig

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#115]
Please take a look at http://piwik.org/ . We want to use it to monitor usage of

1) The API documentation homepage
2) Our APIs

Please write a summary which information we can find out using piwik and how easy it is to setup the monitoring.

The API should give out a chart on which day which endpoint was used how many times.

**Comment by jnehring** [comment]
This is no priority right now.

**Comment by ghsnd** [comment]
We do have some Piwik experience within our lab, so if we can help...

It is fairly straightforward to implement Piwik on the homepage. Just inserting a few lines of Javascript will do the trick. It is also relatively easy to do some custom logging. More in detail: Piwik has custom variables comparable to those of Google Analytics, which can be written using Javascript. It also allows to link visits with a user, once logged in.

There is also a Java client available. So we could maybe use that on the server to track API calls.

If you want to get an idea of what you can see in the reports: check out [their demo](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=32&period=day&date=yesterday#?module=Dashboard&action=embeddedIndex&idSite=32&period=day&date=yesterday&idDashboard=1).

If the reports are not enough, it is possible to access the raw data and process it yourself (you cannot do this with Google Analytics).

**Comment by jnehring** [comment]
Thank you @ghsnd . I think we can use Piwik when we want to introduce API usage monitoring.

**Comment by jnehring** [comment]
this is no longer up to date
