### ISSUE TITLE
Unable to find FREME-NER models

### ISSUE THREAD

**Issue by reckart** [freme-project/technical-discussion#119]
The [FREME documentation](http://api.freme-project.eu/doc/0.6/knowledge-base/freme-for-api-users/freme-ner.html) states that there are Stanford NER models for all the supported languages: English, German, Dutch, Spanish, Italian, French and Russian. Where can one find these models?

**Comment by bgrusdt** [comment]
[These](http://api.freme-project.eu/datasets/ner-trained-models/wikiner/) should be the models you are looking for.

**Comment by reckart** [comment]
@bgrusdt thanks for the quick reply!

Cheez... they are huge! There are no German and Russian models. Are these located elsewhere? May I ask on which corpora these models were trained?

**Comment by jnehring** [comment]
> There are no German and Russian models.

For the German and Russian models we use standard Stanford NER models which are loaded via maven into the system.

> May I ask on which corpora these models were trained?

They were trained on the DBPedia abstracts corpus. http://www.lrec-conf.org/proceedings/lrec2016/pdf/895_Paper.pdf

**Comment by reckart** [comment]
@jnehring The [Stanford website](http://nlp.stanford.edu/software/CRF-NER.shtml#Models) includes  models for English, German, Spanish and Chinese. The CoreNLP maven models artifact that you are using includes the English models. Additionally, I see you are depending on the separate German and Spanish model artifacts. But where did you get the Russian model?

**Comment by reckart** [comment]
@jnehring for the [models that you created](http://api.freme-project.eu/datasets/ner-trained-models/wikiner/), what is their license?

**Comment by jnehring** [comment]
Sorry I was wrong. The russian model was just missing in the folder. I just copied it to http://api.freme-project.eu/datasets/ner-trained-models/wikiner/

The license should be the Apache v2.0 license. But I will check this and let you know.

**Comment by jnehring** [comment]
@reckart the license of the models is creative commons. see https://github.com/freme-project/freme-ner/issues/127
