### ISSUE TITLE
Fork or move repository for the organization

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/technical-discussion#120]
Hi @m1ci , @jnehring 

I would like to transfer the [docker repo](https://github.com/sandroacoelho/freme-docker) ownership  to the organization. How we can manage it?

Best,

**Comment by jnehring** [comment]
I am not sure if it is possible to change ownership. I think we need to re-create the repository. DFKI / @bgrusdt can perform this task. We will

* Open a new repository and copy all the files from [your repo](https://github.com/sandroacoelho/freme-docker) to the new repo.
* Move the documentation to the API documentation homepage.

Did I miss anything? Is this approach ok with you?

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

We can perform this task as you suggested or use transfer ownership in repo settings. 
I transfered right now to @bgrusdt  that can decide to transfer it directly to freme-project or make a new copy.

Best,

**Comment by jnehring** [comment]
Ok thanks @sandroacoelho . So we will first move the repository to the FREME GitHub organization. In a second step we will move the documentation to our documentation homepage but currently I do not know exactly how we do this. I guess we will also change the documentation a bit so first we will only move the repository.

**Comment by bgrusdt** [comment]
I have created a new repository, [freme-docker](https://github.com/freme-project/freme-docker). I imported the freme-docker project into it. Do I have to change any settings or is this sufficient?

**Comment by jnehring** [comment]
thank you! please give infai and dfki teams write access to the new repository.

**Comment by bgrusdt** [comment]
Ok, so this is done. They should have access now.

**Comment by sandroacoelho** [comment]
Great. Thanks!
