### ISSUE TITLE
Installation of FREME across different machines

### ISSUE THREAD

**Issue by ghsnd** [freme-project/technical-discussion#123]
Hi,

Concerning the FREME installation at the partners: it seems to be hard for us at this moment to find a machine with 24 GB of RAM, min. requirements for broker + FREME NER + maybe other services. I.e., we have no budget for that.
However, spreading services over a number of machines with less RAM (e.g. 8GB) might be an option since we can probably find a couple of these.

So how easy is it to install the broker on one machine, FREME NER on another and servers used by FREME NER on yet other machines: I'm thinking about solr and virtuoso on separate machines?
1. Is that possible?
2. Is it documented somewhere?

**Comment by m1ci** [comment]
I believe you can run FREME also on a machine with less then 24 GB by loading fewer language models, and fewer datasets.

**Comment by jnehring** [comment]
It is possible, but a bit complicated. In general things get more complicated the more servers you have. But I can outline the procedure:

* You can install the broker exept FREME NER on server 1. In addition to that, server 1 also hosts MySQL.
* You need a Triple Store (e.g. Virtuoso) and a Solr Server. They might fit into server 1 also, but I am not sure. They communicate via HTTP APIs so it should be possible to put them on other servers.
* You can install multiple FREME NER instances in server 2 and 3. I think for all models you need more then 8 GB ram, but they fit in 2 instances of 8 GB ram each. You can either call these FREME NER instances directly, without involving the broker. Another method is that you can use the proxy service in the broker to redirect to the FREME NER instances. In the later case you would have URLs like /e-entity/freme-ner/de_en_ru for German, English, Russian and /e-entity/freme-ner/it_es_nl for Italian, Spanish and Dutch.

**Comment by jnehring** [comment]
closing the issue because there is no more discussion
