### ISSUE TITLE
XSLT transformation

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#126]
I tried to run the XSLT based processing of a TEI document via the Toolbox/XSLT-Converter but it does not work. 
https://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox%2FXSLT-Converter/post_toolbox_xslt_converter_documents_name

I use the provided example with the tei2temp-html 

@jnehring @ArneBinder @fsasaki do you have any idea why it is not working?

**Comment by fsasaki** [comment]
I tried the example, see attached curl request, and it works. @m1ci , can you provide your request as curl?
[xslt-example.txt](https://github.com/freme-project/technical-discussion/files/560369/xslt-example.txt)

**Comment by m1ci** [comment]
I just tried again and it works. Thanks and sorry for the noise.
