### ISSUE TITLE
wiki page "Server Infrastructure" is empty

### ISSUE THREAD

**Issue by jowagner** [freme-project/technical-discussion#130]
https://github.com/freme-project/technical-discussion/wiki/Server-Infrastructure linked from https://github.com/freme-project/technical-discussion/wiki needs content.

**Comment by jnehring** [comment]
this wiki is outdated. we should delete it. please check the documentation homepage: https://freme-project.github.io

the knowledge base has a section "FREME for system administrators". you should find the page you are looking for there.

**Comment by jowagner** [comment]
Thanks. In the meantime, I added a link to the KB to the empty page.

**Comment by jnehring** [comment]
i switched off the wiki to avoid similar problems and added a link to the documentation homepage to the readme of this repository
