### ISSUE TITLE
Add licensing information to FREME

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#39]
FREME is going to be released under [Apache 2 License](http://www.apache.org/licenses/LICENSE-2.0). We need some modifications in our source codes / distributions

* Add license headers to all our source code files. We should try using the [License Maven Plugin](http://code.mycila.com/license-maven-plugin/) as Milan suggested.
* Update the list of [3rd party tools in FREME](https://docs.google.com/document/d/1YDtgIt_50qocBmcNf2NS8HzIW9H_2dhuKyC2K5qHCRY/edit#heading=h.hdl92vmow8xd) and their license information
* Most 3rd party tools are licensed under Apache 2 also. We need to generate the NOTICE files, maybe using [maven notice plugin](https://wiki.jasig.org/display/LIC/maven-notice-plugin)
* We need to find out how to generate NOTICE files (or something similar) for 3rd party tools under other licenses.
* Special case is epublib because we use a modified version of a project released under GPLv3.

**Comment by jnehring** [comment]
[This suggestion](http://programmers.stackexchange.com/questions/234511/what-is-the-best-practice-for-arranging-third-party-library-licenses-paperwork) sounds like a good best practise on how to make FREME public without getting in jail:

1) Source files: all my files have the AGPL header. All 3rd party files are left (mostly) unmodified, and therefore include their own license header.

2) LICENSE.txt, at the root of the package, contains the AGPL license text (as explained in the "How to Apply These Terms to Your New Programs" section).

3) A secondary license file, which I named LICENSE-3RD-PARTY.txt, also located at the root of the package, contains verbatim copies of ALL licenses. For each license, a header states which license it is, and which part it applies to. I also include the name of the copyright holders here - I reuse them somewhere else afterwards so it's worth the effort.
```
-----------------------------------------------------------------------------
                        The MIT License (MIT)
        applies to: 
        - AJAX Upload, Copyright (c) Andrew Valums
        - jQuery hashchange event, Copyright (c) 2010 "Cowboy" Ben Alman
        - jquery.hotkeys, Copyright (c) 2010 John Resig
-----------------------------------------------------------------------------

Permission is hereby granted, free of charge [...]
```
4) README.txt, also at the root, explains that the software is AGPL (see LICENSE.txt) and uses third party libraries that are distributed under their own terms (see LICENSE-3RD-PARTY.txt)

5) In the on-line documentation, I have a License page that repeats the information from the readme: my software is AGPL, and it uses 3rd party components that are BSD/MIT/[...]. I have decided to keep this page cleaner and more readable, therefore only the name of the license is provided, with a link to the full text, and the name of the copyright holders with a link to their own website.
```
jQuery
    Copyright 2013 jQuery Foundation and other contributors
    http://jquery.com
    MIT License
Data Driven Documents (D3)
    Copyright (c) 2013, Michael Bostock    <-- link to personal website, if any
    http://d3js.org                        <-- link to software website
    BSD-like license                       <-- link to license full text
[...]
```
6) Also in the on-line documentation, I have a Credits page, where I list the direct and indirect main contributors. I have for instance cited the PostgreSQL group, although PostgreSQL is not included in the download, but you need it to run the software. This would be a good place to place all acknowledgements that are either required or desired by the authors of 3rd party tools/libraries/etc.

**Comment by ArneBinder** [comment]
Step 1), 2) and 3) are done.
The license-maven-plugin uses [this](https://raw.githubusercontent.com/mycila/license-maven-plugin/master/license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/APACHE-2.txt) as template.

**Comment by ArneBinder** [comment]
Every eservice-project (except freme-ner) and the broker has a license branch now.

**Comment by ArneBinder** [comment]
3rd party licenses tool #62

**Comment by jnehring** [comment]
### Next steps

* change output of licensing tool.:
Example Output für 3rd-party-licenses.txt, when all information is present
```
Spring Boot - spring-boot-maven-plugin, Copyright 2014 Paul Siegmann, http://www.siegmann.nl
```
* work over the [licensing table](https://docs.google.com/spreadsheets/d/1j2XPwjRLTjyxFm0ceFf_Ts1tmigZEc-YatAWEaciz8k/edit#gid=1205886148)
* Change Readme.md in all projects
    * Use format of https://github.com/freme-project/Services
    * Add last sentence from here: https://github.com/freme-project/Broker/tree/license
* Finish ConversionServices first in the license branch and show it to @jnehring
* Merge everything in master

**Comment by ArneBinder** [comment]
**Next Steps** are implemented. All src files of all freme-projects are checkt for the license header. @jnehring can we close this issue?
