### ISSUE TITLE
Incorrect MIME Type "application/json+ld" in all services except e-Link

### ISSUE THREAD

**Issue by josauder** [freme-project/technical-discussion#40]
In FREME every API call except E-Link sends responses with the Content-Type Header "application/json+ld". However, it seems that the correct name for this MIME Type is "application/ld+json".

See the JSON-LD [specification](http://www.w3.org/TR/json-ld/) and the [Wikipedia article](https://en.wikipedia.org/wiki/JSON-LD).

E-Link sends responses with the correct header.

Should this be changed in almost all of our project?

**Comment by jnehring** [comment]
+1 for changing all JSON LD content-type headers to `application/ld+json`

**Comment by jnehring** [comment]
I changed that. For downwards compatibility `application/json+ld` still works
