### ISSUE TITLE
[AGROVOC] Response value from e-terminology/tilde using Agrovoc

### ISSUE THREAD

**Issue by giorgos1987** [freme-project/technical-discussion#41]
Getting response calling http://api-dev.freme-project.eu/current/e-terminology/tilde  for agrovoc terms i noticed that returns also 
 "termInfoRef" : [ ":618662", "http://aims.fao.org/aos/agrovoc/c_6145" ]

For what stands the first value of termInfoRef (:618662) ?

Response:

{
  "@graph" : [ {
    ..... }
  }, {
...
    "referenceContext" : "http://freme-project.eu/",
    "term" : "yes",
    "termInfoRef" : [ ":618662", "http://aims.fao.org/aos/agrovoc/c_6145" ]
  }, {
....
    },
    "referenceContext" : "http://freme-project.eu/",
    "term" : "yes",
    "termInfoRef" : "http://aims.fao.org/aos/agrovoc/c_3848"
  },

**Comment by jnehring** [comment]
@andish is on vacation. Maybe @tatgor  can help out?

**Comment by tatgor** [comment]
This is an internal term ID to "poultry", URI is not available at the moment. TBD

**Comment by stoitsis** [comment]
Hi, is this happening cause you have not imported the latest version of Agrovoc? Cause poultry URI exists in Agrovoc http://aims.fao.org/skosmos/agrovoc/en/page/c_6145

**Comment by tatgor** [comment]
In your example, there are two references: "618662" and "http://aims.fao.org/aos/agrovoc/c_6145", which correspond to two terms "poultry". The two terms are found by the service and returned in response to your request.
1) The first reference "618662" is an internal numerical term ID: 618662, which is assigned to the term "poultry" stored initially in the Tilde database. URIs for internal terms are not available at the moment as the process of their assignment is under development in FREME. That is why you get a numerical ID solely. As soon as we are ready, there will be URI(s) returned by the service, not plain numbers also for internal terms in addition to AGROVOC terms.
2) "http://aims.fao.org/aos/agrovoc/c_6145" is an original AGROVOC URI, which links to the term "poultry" stored originally in the AGROVOC database, however imported to the Tilde database for FREME. You can notice AGROVOC URIs also have a numerical part (for "poultry" it is 6145), which comes from previous term IDs in AGROVOC before its conversion to RDF/SKOS. More info here: http://aims.fao.org/standards/agrovoc/faq#How are AGROVOC URIs assigned?.
I can imagine the list of resources to query can be customised by the user, e.g., you would like to query AGROVOC and not other databases - this can be further discussed with Andis @andish.

**Comment by andish** [comment]
Yes, all is true what @tatgor said.
There are two type of term references:
1) **Tilde Terminology references** - references to Tilde Terminology concepts. If you see full response you will find that base path is definied as "https://term.tilde.com/terms/"
```

type": "http://purl.org/dc/terms/type",
    "source": "http://purl.org/dc/elements/1.1/source",
    "decomp": "http://www.w3.org/ns/lemon/decomp#",
   "@base": "https://term.tilde.com/terms/",
    "": "https://term.tilde.com/terms/",*
    "prov": "http://www.w3.org/ns/prov#",
    "nif": "http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#",
    "itsrdf": "http://www.w3.org/2005/11/its/rdf#",
    "void": "http://rdfs.org/ns/void#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "dcat": "http://www.w3.org/ns/dcat#",
    "tbx": "http://tbx2rdf.lider-project.eu/tbx#",
    "dct": "http://purl.org/dc/terms/",
    "ontolex": "http://www.w3.org/ns/lemon/ontolex#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "ldr": "http://purl.oclc.org/NET/ldr/ns#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "cc": "http://creativecommons.org/ns#",
    "odrl": "http://www.w3.org/ns/odrl/2/""
```
so these Tilde Terminology references not just internally available, but discoverable over HTTP https://term.tilde.com/terms/618662 [it will return full information by the end of this week].
Also all information about terms are included in response. (find skos:Concept with id=618662)

2)**External references** Currently there are only references to AGROVOC dataset. You have to retreive information from there, we are just referencing to them (not making offline copies of data).
Unfortunately this service is down for now: 
http://aims.fao.org/aos/agrovoc/c_6145

```
Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.2.15 (Red Hat) Server at aims.fao.org Port 80''
```

**Comment by andish** [comment]
@stoitsis > Hi, is this happening cause you have not imported the latest version of Agrovoc? 
we have imported latest version [agrovoc_2015-03-24_core.rdf] available here:
https://aims-fao.atlassian.net/wiki/display/AGV/Releases
