### ISSUE TITLE
API home page

### ISSUE THREAD

**Issue by ghsnd** [freme-project/technical-discussion#42]
If one happens to surf to http://api.freme-project.eu/, one sees the Apache2 Ubuntu Default Page. Maybe this can be replaced by something more useful...

**Comment by jnehring** [comment]
Good idea. We could embed this in a bigger idea for improving the documentation:

* Index page at http://api.freme-project.eu/. It has links / explanatory text to all sub pages and also a link to technical discussion wiki, to http://freme-project.eu and to our [GitHub organization page](https://github.com/freme-project/).
* one subpage is the current api documentation http://api.freme-project.eu/doc/0.2. 
* Then we can have another page subpage "FREME showroom" that shows the examples felix send around today.
* A page for datasets (auto generated via Javascript and API call)
* A page for templates (auto generated via Javascript and API call)
* A license page
* A credits page saying thank you to all the 3rd party libraries that FREME uses. Not sure if this is necessary though...

This would mean we introduce a second homepage. We have to discuss if this is necessary or if we integrate all this in our current homepage.

**Comment by ghsnd** [comment]
In the case that all this would be integrated in the current homepage, a solution can be a simple redirect towards the homepage. However, http://api.freme-project.eu/ could be *the* page for developers using the API, while the current home page is more general about the FREME project. To be discussed indeed.

**Comment by jnehring** [comment]
moved to https://github.com/freme-project/Documentation/issues/58
