### ISSUE TITLE
[pipelining] Pipelining testing report

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#44]
The results from the testing are summarized in this document
https://docs.google.com/document/d/18rWHyzumcbaHTeF1LvbjC7v9Q4wbRAk5qPZ8z-F2oRw/edit#

For each failed test or question, an issue was created under the pipelining repo issues list: https://github.com/freme-project/pipelines/issues

**Comment by ghsnd** [comment]
I assume this can be closed now...
