### ISSUE TITLE
EOL Java 7

### ISSUE THREAD

**Issue by ghsnd** [freme-project/technical-discussion#45]
Since Java 7 is [not supported anymore](http://www.oracle.com/technetwork/java/javase/documentation/eol-135779.html) by Oracle (i.e. no more bug fixes), it might be a good idea to migrate to Java 8 in some future release. This has also some advantages at language level as well...

**Comment by jnehring** [comment]
Good point. We will do this in FREME 0.4

**Comment by jnehring** [comment]
Java 8 is not in the official repositories of ubuntu. So we need to add ppa `ppa:webupd8team/java` and then install package `oracle-java8-installer` to install java 8.

**Comment by jnehring** [comment]
* installed java8 on freme-dev, freme-live. It was already installed on freme-worker
* added new jdk to jenkins on freme-dev
* updated java version for maven compiler plugin in all projects
* Updated [Developers getting started guide](https://github.com/freme-project/technical-discussion/wiki/Developers-getting-started-guide)

# When you have problems compiling FREME then you might have to update your JDK and JRE to Java 8!!!
