### ISSUE TITLE
e-Link default template for "everything"

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#49]
@fsalliau asked for a template that gives back all rdf triples related to an entity. It should be the default template when no template is specified. It can be used to explore a SPARQL endpoint through FREME. I find it is a useful feature.

The open question is how to define the SPARQL endpoint. Possible solutions:

a) We make a new endpoint `/e-link/explore` with a parameter "endpoint". It can be used to explore an endpoint.
b) It runs against one predefined endpoint, e.g. dbpedia
c) It runs against a set of predefined endpoints, e.g. dbpedia, europeana and geonames.

**Comment by fsasaki** [comment]
If linked data fragments are used one can specifiy in the linked data fragments setup (a json-file) the sparql endpoints or (compressed) RDF dumps to be queried. That may also be an option - a variant of c),

**Comment by fsalliau** [comment]
Hi @jnehring 

My idea was to keep the /e-link/documents/ endpoint and omit the templateId.
But, looking at the documentation, I see there's no parameter for the dataset that should be queried (as it is defined by the SPARQL in the template). The nickle dropped - a little late  ;)

What would be the most practical approach?
Option a, with a parameter for the endpoint?
So e.g. that would be /e-link/explore with parameter http://dbpedia.org/page/Ai_Weiwei

**Comment by jnehring** [comment]
@fsalliau I also think that option a) suits your use case the best

**Comment by fsalliau** [comment]
Ok. Can you put it on the roadmap?

**Comment by jnehring** [comment]
@m1ci you have any thoughts on this?

**Comment by m1ci** [comment]
1) A best practice for retrieving information about particular resource is simply to dereference the resource and retrieve its representations.
For example, to retrieve the representation of the http://dbpedia.org/resource/Ai_Weiwei resource, you can use the following command:

    curl -vL http://dbpedia.org/resource/Ai_Weiwei -H "Accept:text/turtle"

I remember in Turin I suggested this to @fsalliau but he said that this is not appropriate for their use case - which I don't recall why. @fsalliau can you please state what was your position on my suggestion above? also, why current templating mechanism is not feasable?

2) we can have a generic template `select * where {@@@enity_uri@@@ ?p ?o}`, which is executed against specified dataset or SPARQL endpoint. The endpoint can be specified with a param `dataset=dbpedia` or `endpoint=http://dbpedia.org/sparql`. For the `dataset` param, we can have a list of datasets with a corresponding endpoints.

3) if 1) and 2) are not feasable we can introduce an endpoint `/e-link/explore` with param `describe=http://dbpedia.org/resource/Ai_Weiwei` which will dereference the URI at the server-side and return info to the client.

What do you think?

**Comment by fsalliau** [comment]
@m1ci imho the currently templating system is introducing unnecessary complexity.
People who are not familiar with SPARQL should be able to use the e-services without needing to create templates. 
I think it would be useful to make it possible to retrieve all RDF triples from a certain endpoint as in the example above. @jnehring 's solution looks fine to me.
Of course you can dereference the endpoint, but I think we should provide a small FREME wrapper for consistency.

**Comment by m1ci** [comment]
> @m1ci imho the currently templating system is introducing unnecessary complexity.

for some scenarios such as yours, yes.

OK, so when retrieving all triples for a resource we need to know:
1) which resource we want to describe
2) which endpoint should be used
3) what type of endpoint is it (LDF or standard SPARQL)

So we can introduce `/e-link/explore` with three params:
- `resource` - the resource URI
- `endpoint` - the endpoint URL
- `endpoint-type` - the type of the endpoint, `ldf`, or `sparql`

any thoughts on this?

**Comment by jnehring** [comment]
I think we have specified this issue enough. I created freme-project/e-Link#41 as the issue for implementing this feature. I added the default value `sparql` for parameter `endpoint-type`
