### ISSUE TITLE
e-Terminology - new parameters

### ISSUE THREAD

**Issue by andish** [freme-project/technical-discussion#52]
Must implement  in Freme server and also in Tilde API new parameters:
* collectionID - already done in Tilde API. Do markup with single collection/dataset
* mode - terminology spotting mode: 
 * light - just anotate terms, 
 * full - include also full term data [lemon].

I am open for suggestions for better parameter names & values

**Comment by m1ci** [comment]
1) like the param `mode`

2) its not clear to me what `collectionID` param will allow. Is it a `domain` thing?

**Comment by andish** [comment]
Collection is more like a single dataset. 
*E.g., AgroKnow or Wripl can upload their own terminology data as new collection [dataset] and use it for enrichment instead of enriching with all Tilde Terminology available terms.*

Domain is an item from our classification system to whom can be each collection mapped/assigned. So -if any domain chosen - then enrichment is performed with a set of terms from collections who  has mapping to that domain [clasification unit].

**Comment by andish** [comment]
implemented at https://github.com/freme-project/Broker/issues/125
