### ISSUE TITLE
e-Translation: add support for ITS 2.0 data categories

### ISSUE THREAD

**Issue by andish** [freme-project/technical-discussion#54]
- **Translate** – already supporting
- **Terminology** – we have to discover translation variants from ITS references.
- **MT Confidence** – MT will add information to the output

These categories specifies preferred MT system:
- **Language information** – choose corresponding MT
- **Domain** – choose corresponding MT.

Andis: _What happens if no MT system available for this domain?_
Felix: _Have a fallback language or an error. And, language information may be in conflict with parameters in the FREME service call. In that case these parameters probably should be stronger._

Post MT process adds to the output ‘Localization quality issue’ if breaks the rule defined in these categories:
- **Allowed characters**
- **Storage size**

Other categories must transport to the output:
- Localization Note
- Provenance  
- External resource
- Target pointer
- ID Value
- Localization quality issue
- Localization quality rating
- Directionality
- Elements within text 

NIF samples with ITS data categories provided by @fsasaki:
https://drive.google.com/drive/folders/0B_Fh3PcCczdRMjk0dEh3b1ZQY3c

**Comment by fsasaki** [comment]
The sample file referenced by @andish now contains examples for all data categories in above list, except: provenance and localization quality rating.

**Comment by andish** [comment]
@fsasaki i have question about its:mtConfidence category. As any isString object can contain multiple rdf:target categories for multiple languages, but its:mtConficence not language aware and for each target translation must have its own mtConfidence attribute.
```
<http://example.com/exampledoc.xml#char=1523,1555> 
    nif:isString "Capital of England";
     ....    
    itsrdf:mtConfidence "0.6982";
    itsrdf:target "Anglijas galvaspilsēta"@lv;
    itsrdf:target "Inglismaa pealinna."@et;
    itsrdf:target "Anglijos sostinėje"@lt;
    itsrdf:term "no";
    itsrdf:translate "yes";
    itsrdf:withinText "no".
```

also same for other categories - localizatioNote, allowedCharacters, storageSize.This is target [translation] aware information

**Comment by fsasaki** [comment]
For localizatioNote, allowedCharacters, storageSize, I think these
categories can also be applied to source content. See an XML example e.g.
for storage size
http://www.w3.org/TR/its20/examples/xml/EX-storageSize-local-1.xml
but you are right about mt confidence that this should be applied to the
translated string and above categories could also be applied to the
translated string.
@m1ci , should the model for translated text be changed? Andis' example
shows that translated text (like normal text) in many cases needs to be the
subject of triples. So representing translated text as a string with
itsrdf:target property does not work.


2015-10-13 15:48 GMT+02:00 Andis <notifications@github.com>:

**Comment by m1ci** [comment]
First of all, this issue is affecting not only e-Translation, but also e-Entity and e-Terminology.

> @m1ci , should the model for translated text be changed?

Definitely yes.

> Andis' example shows that translated text (like normal text) in many cases needs to be the subject of triples. So representing translated text as a string with `itsrdf:target` property does not work.

Similar cases motivated the extension of NIF and NIF 2.1 can help here. Let me explain how.
In NIF 2.0 we introduce new class `nif:AnnotationUnit`, which can be interpreted as an annotation over a string, and `nif:annotationUnit` which links `nif:String` with `nif:AnnotationUnit`. This allows us to have multiple annotations over a same String. Relating this to the translation use case, you can have `nif:String` which represents the content for translation, and `nif:AnnotationUnit` which represents each individual translation. Furthermore, you can attach the confidence to the annotation units. Bellow is new model for your example:
```
<http://example.com/exampledoc.xml#char=1523,1555> 
    nif:isString "Capital of England";
    itsrdf:term "no";
    itsrdf:translate "yes";
    itsrdf:withinText "no";
    nif:annotationUnit [
        itsrdf:target "Anglijas galvaspilsēta"@lv;
        itsrdf:taConfidence "0.6982"^^xsd:decimal ;
    ] ;
    nif:annotationUnit [
        itsrdf:target "Inglismaa pealinna."@et;
        itsrdf:taConfidence "0.1111"^^xsd:decimal ;
    ] ;
    nif:annotationUnit [
        itsrdf:target "Anglijos sostinėje"@lt;
        itsrdf:taConfidence "0.2222"^^xsd:decimal ;
    ] .
```

**Comment by m1ci** [comment]
I compiled an example which combines e-Entity, e-Terminology and e-Translation. See https://docs.google.com/document/d/1AzR2P7SBR-L7IJ_vsGNbDx21bXnxky9bSwqC8rSGuAw/edit
Any input is more than welcome.

**Comment by fsasaki** [comment]
Thanks, @m1ci , makes sense to me. Should we tell @andish that he should implement e-Translation in this way? Is that documented somewhere so that we can have a look?

**Comment by jnehring** [comment]
@andish Can we close this issue?

**Comment by andish** [comment]
> I compiled an example which combines e-Entity, e-Terminology and e-Translation
This is not implemented and I think the final solution not decided. But this can be moved to prototype v0.5. 

From other aspects this issue can be closed

**Comment by jnehring** [comment]
this is no longer up to date and can be closed.
