### ISSUE TITLE
location for hosting datasets dumps

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#55]
At which server should we host the dumps of the FREME generated datasets?
Freme NER, Freme live, Freme dev?

**Comment by m1ci** [comment]
we can also have page, for example, running at `http://www.freme-project.eu/datasets/` which will provide description and pointers to each dataset

**Comment by jnehring** [comment]
We can host them on FREME live server. We have ~1 TB of free disk space there. And we should add the datasets to the homepage, therefore I link to freme-project/Documentation#58

**Comment by m1ci** [comment]
ok, great.
