### ISSUE TITLE
Evaluate integrating Japanese into FREME NER

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#57]
Requirement by @freme-project/vistatec  . More information in [Specification of FREME 0.4](https://docs.google.com/document/d/1djp_pkUiAbTaGB8IrXckS_Ngz1j6HqPb3erepYn_htA/edit#bookmark=id.xn02fi2mtuj4)

**Comment by m1ci** [comment]
providing support for Japanese needs more work primarily in collecting and processing training data. Therefore, we won't be able integrate Japanese in FREME 0.4.

**Comment by jnehring** [comment]
Ok no problem. Lets keep it in mind while specifying FREME 0.5

**Comment by jnehring** [comment]
this is no longer up to date
