### ISSUE TITLE
Evaluate integrating Russian in FREME NER

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#58]
Requirement by @freme-project/vistatec  . More information in [Specification of FREME 0.4](https://docs.google.com/document/d/1djp_pkUiAbTaGB8IrXckS_Ngz1j6HqPb3erepYn_htA/edit#bookmark=id.xn02fi2mtuj4)

Related to #57

**Comment by m1ci** [comment]
we provided the first prototype with support for Russian. `language=ru`

**Comment by jnehring** [comment]
Nice. I tested it with some russian text in kyrillic and it produced some outputs. However since I do not understand russian I cannot evaluate it.

**Comment by m1ci** [comment]
I tried the first paragraph from https://russian.rt.com/article/121858
```
curl -v -d "Воздушно-космические силы РФ уничтожили два командных пункта группировки «Исламское государство» в районе Дейр-эз-Зор в Сирии, а также завод боевиков по производству вооружения. Между тем экстремисты оборудовали позицию в нескольких километрах от авиабазы в Сирии, на которой располагаются российские военные. Более 40 группировок, в том числе «Аль-Каида», пообещали нанести удары по российским силам. Подробнее о том, какое вооружение используется для защиты авиабазы в Латакии — корреспондент RT Мурад Газдиев." -H "Content-Type: text/plain; ; charset=UTF-8" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&outformat=turtle&language=ru&dataset=dbpedia"
```
... and it recognizes 4 entities: "Исламское государство" - islamic terrorist group, "Воздушно-космические силы РФ" - air forces of Russia, "Сирии" - Syria, and "Дейр-эз-Зор" - city in Syria. 

Its not perfect but IMO provides meaningful results.

PS: I can read cyrillic and understand little Russian and some other slavic languages ...

**Comment by jnehring** [comment]
What is the state of this task? You write "first prototype". Can we state that FREME NER understands russian now? That means we update the documentation. Or does this task need further work.

**Comment by m1ci** [comment]
> What is the state of this task? You write "first prototype". Can we state that FREME NER understands russian now? 

Yes, feel free to write that.

> That means we make russian an official feature of FREME NER and update the documentation accordingly. Or does this task need further work?

From my basic understanding of cyrillic and Russian, I can say it spots entities "well" and links them appropriately. Some further work is needed for the linking part, but this is something that is needed also for the other languages.

**Comment by jnehring** [comment]
Thanks @m1ci 

@josauder please update the documentation of POST /e-entity/freme-ner/documents and add the value `ru` to the list of supported languages.

**Comment by josauder** [comment]
@m1ci  Does this mean that russian is also a permitted language for the submission/management of freme-ner datasets?

**Comment by m1ci** [comment]
yes: "en", "de", "nl", "it", "fr", "es", "ru"
