### ISSUE TITLE
Specification of CRUD Pipelines

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#62]
Please write a specification for create, read, update, delete endpoints for pipelines.

**Comment by ghsnd** [comment]
## Create pipeline

Creates and stores a pipeline on the server the request is sent to.
The response contains the id of the created pipeline, which is to be used in further methods.

**Method**: `POST`

**Endpoint**: `/pipelining/templates/`

**Content-Type**: HTTP Header parameter, should be `application/json`

**timetolive**: Optional parameter: number of days the pipeline should exist on the server. If not given, it defaults to one day.

**Body**: The pipeline as JSON object, as described in `/pipelining/chain`, but without the *body* field.

**Response**: 

* `200 OK` with the generated *pipelineid* in the body if everything goes well. The `Expires` HTTP header indicates when the pipeline will be deleted.
* `400 BAD REQUEST` if the request cannot be processed. 

## Update pipeline

Updates a pipeline on the server the request is sent to.

**Method**: `PUT`

**Endpoint**: `/pipelining/templates/{pipelineid}` 

**Content-Type**: HTTP Header parameter, should be `application/json`

**pipelineid**: Path parameter: the id of the pipeline

**Body**: The pipeline as JSON object, as described in `/pipelining/chain`, but without the *body* field.

**Response**: `200 OK` if all goes well; `400 BAD REQUEST` if the request cannot be processed; `404 NOT FOUND` if the pipeline does not exist.

## Read (get) pipeline(s)

Returns the pipeline with the given id, or a list of pipelines if no id is given.

**Method**: `GET`

**Endpoint**: `/pipelining/templates/{pipelineid}`

**pipelineid**: Optional path parameter: the id of the pipeline. If no id given, all pipelines are returned.

**Response**: `200 OK` with as body the pipeline(s) as JSON object, as described in `/pipelining/chain`, but without the *body* field; `400 BAD REQUEST` if the request cannot be processed; `404 NOT FOUND` if the pipeline does not exist.

## Delete pipeline

Deletes the pipeline with a given id.

**Method**: `DELETE`

**Endpoint**: `/pipelining/templates/{pipelineid}`

**pipelineid**: Path parameter: the id of the pipeline

**Response**: `200 OK` if all goes well; `400 BAD REQUEST` if the request cannot be processed; `404 NOT FOUND` if the pipeline does not exist.

## Use pipeline:

Update to the existing `/pipelining/chain` documentation: if no pipelineid parameter is given: see the existing documentation.
If not given: see documentation below.

**Endpoint**: `/pipelining/chain/{pipelineid}`

**pipelineid**: Optional path parameter: the id of the pipeline to use. If not given: see the existing documentation.

**Content-Type**: HTTP Header parameter: should be the content-type of the first service in the pipeline.

**body**: The content to use as input for the pipeline. 

**Response**: `200 OK` if all goes well; `400 BAD REQUEST` if the request cannot be processed; `404 NOT FOUND` if the pipeline does not exist.

**Comment by jnehring** [comment]
Nice work! Just some comments on the create pipelines endpoint:

> timetolive: Optional parameter: number of days the pipeline should exist on the server. If not given, it defaults to one day.

I think timetolive is a rather complicated parameter. A parameter `persist` with possible values `true, false` that implies a timetolive of 1 week would be easier to understand for the user.

When you want to use timetolive, then we also need a possible `timetolive=-1` which means it persists forever.

> 200 OK with the generated pipelineid in the body if everything goes well. The Expires HTTP header indicates when the pipeline will be deleted.

How about JSON? Something like
```
{
    "id": 123
}
```

I think this is more self explaining then just returning a number.

**Comment by ghsnd** [comment]
> Nice work! Just some comments on the create pipelines endpoint:
> 
>     timetolive: Optional parameter: number of days the pipeline should
>     exist on the server. If not given, it defaults to one day.
> 
> I think timetolive is a rather complicated parameter. A parameter
> |persist| with possible values |true, false| that implies a timetolive
> of 1 week would be easier to understand for the user.
> 
> When you want to use timetolive, then we also need a possible
> |timetolive=-1| which means it persists forever.
> 
>     200 OK with the generated pipelineid in the body if everything goes
>     well. The Expires HTTP header indicates when the pipeline will be
>     deleted.
> 
> How about JSON? Something like
> 
> |{ "id": 123 } |
> 
> I think this is more self explaining then just returning a number.
> 

OK, updated the spec taking these remarks into account.

**Comment by jnehring** [comment]
I think the specification is finished. Implementation is handled by https://github.com/freme-project/pipelines/issues/17
