### ISSUE TITLE
Integrating FREME NER into the Broker

### ISSUE THREAD

**Issue by nilesh-c** [freme-project/technical-discussion#63]
Here's the current entry point of the FREME NER server: https://github.com/freme-project/freme-ner/blob/master/src/main/scala/org/elinker/core/api/Server.scala

This is like a Spring Boot app (I don't have much experience with Spring but from the docs this looks like the closest equivalent).

I can see two ways to integrate FNER into the Broker:
* I can write a Java wrapper for this (that'll be filled with all the necessary configuration options) for use inside the Broker. Since this is maven-ready, you'd include the freme-ner artifact (it's currently called elinker, will change it) into the Broker pom.xml, instantiate the Java object with the config options (SOLR IP:PORT, path to models, MySQL address) and go from there. When FNER is running on its own node, apart from the rest of the configuration options, you should also provide the address to the eureka server (if I understand this correctly, because FNER will have some spring cloud client code to register itself on the eureka server I guess), unless if it's running completely standalone.

OR

* I can use spray-servlet and package the app into war that you can deploy into Tomcat or some other servlet container, make it read the configuration from XML files. But I frankly wouldn't recommend that because for users that means another headache (setting up a servlet container and messing with XML configs).

@jnehring let's have a discussion on this.

**Comment by jnehring** [comment]
I suggest a modification of your first idea with the Java wrapper.

* FREME NER is treated as a java library. In the freme-ner repository there is no standalone server. It exposes an API with (at least) one functionality.
* The freme-ner repository will get new classes
    * `FremeNERAPI`: This class exposes the Java API through one or multiple java methods. So from the outside all complexity of FREME NER hides behind this class. It is annotated with @Bean so it can be injected in the Broker as Spring Bean. FremeNERAPI is a Singleton. All the methods should be thread safe because they can be called concurrently.
    * `FremeNERConfig` This class offers the spring bean. It contains only a few lines of code and exposes the Spring Bean to the outside world.
* We can either use [Spring Scala](https://github.com/spring-projects/spring-scala) to implement the bean and config. I think that Spring Scala is something for people who know both Spring and Scala. Or we use standard Java. @nilesh-c do you think we can have a normal Java class in freme ner repository that calls the Scala code? Then we could implement `FremeNERAPI` and `FremeNERConfig` in standard Java and make the bridge here. This seems to be the easiest solution to me.
* When we have standard java classes then we can also inject configuration values in the standard spring way in `FremeNERAPI`. If not then we have to read Spring Scala manual and do it the Spring Scala way.
* The REST endpoint will move to the broker then and will be newly implemented the same way like all other endpoints. https://github.com/freme-project/Broker/issues/96 will ensure that it is possible to start FREME either as Broker or FREME NER.

@nilesh-c I think a call might help...

**Comment by nilesh-c** [comment]
I would be willing to add a Java API, which means the repository will have the spray-based REST API and the Java API, separate from each other. I can create a simple `FremeNER` and its corresponding plain Java config class that you can reuse in building your Spring classes/beans (which I would suggest to keep in the broker repo, for separating concerns).

**Comment by nilesh-c** [comment]
@jnehring I'm trying to understand why exactly we need the Spring Cloud setup. Scaling and load-balancing is very much dependant on individual preferences and users or business wanting to setup FREME e-Services on their machines would want to use the means they think are best (including caching and what not).

Therefore, why do we need a complicated setup right now? Can't we do with a really simple setup like this for now to scale the system (https://docs.google.com/document/d/1qa2Ec7W8zwD0W20q38CSB2j33GNWt0Gtv-ii75hGT9s/edit?usp=sharing)?

 I'm sorry if I overlooked it if you already outlined the reasons.

**Comment by jnehring** [comment]
Lets move the discussion on whether to use NGINX or Spring Cloud to #68 and focus on the integration of your Scala codes in the Java broker here. We need to do this task anyways, even without the cloud setup.

**Comment by jnehring** [comment]
We will integrate FREME NER in the broker with the new architecture update. So this ticket becomes invalid.
