### ISSUE TITLE
Choose tool for load testing of FREME

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#64]
We want to measure how long it takes to process a certain dataset of e.g. 1000 documents with FREME NER. See related discussions in minutes of [Developers call from 23rd September](https://docs.google.com/document/d/1BepI1SMWAX4eY_iva9BacuZbpuLG792kM5tkmwzcy0E/edit?usp=drive_web) and [FREME NER and Big Data](https://docs.google.com/document/d/1ipfDmYdxWbvdLTUS096CzC7gRij8T4nGyR-uDr90IUE/edit?usp=drive_web).

We also want to find out how to use FREME as efficient as possible to process a large number of entities. Therefore we have to answer the question how many requests should be send to FREME in parallel.

We are discussing to choose between Gerbil and Apache JMeter.
@xFran @m1ci @nilesh-c please comment.

The dataset for this test is defined in https://github.com/freme-project/freme-ner/issues/24

So my opinion:

* Gerbil can send the requests one after another to FREME so it can give an answer to how long it takes to process 1000 documents.
* When we scale out FREME NER, then Gerbil cannot measure the speed because this requires us to send concurrent requests.
* The advantage of Gerbil is that it performs quality measurement also. So we get the quality measurement for free.
* The advantage of Apache JMeter is that it can also do concurrent requests.
* The open question is, if Apache JMeter can send the whole dataset to FREME NER. Or if it can only do the same request many times.

So my conclusion would be that Apache JMeter is better suited for our tests, when the open question (last bullet point) is solved. Gerbil is not suited because it cannot do the concurrent tests.

**Comment by m1ci** [comment]
> We are discussing to choose between Gerbil and Apache JMeter.

Gerbil can be used for measuring "quality of enrichments and speed performance (docs per sec)" and JMeter for "performance" only.

> Gerbil can send the requests one after another to FREME so it can give an answer to how long it takes to process 1000 documents.

Correct.

> When we scale out FREME NER, then Gerbil cannot measure the speed because this requires us to send concurrent requests.

We can write simple bash script and measure this. @nilesh-c what do you think? 

> The advantage of Gerbil is that it performs quality measurement also. So we get the quality measurement for free.

Correct, also the results are then comparable with other tools which were evaluated with the same datasets.

> The open question is, if Apache JMeter can send the whole dataset to FREME NER. Or if it can only do the same request many times.

We have no experience with JMater, so hard to say. I think with bash script we can easily send concurrent request and measure how much time it took to process all the requests.

> So my conclusion would be that Apache JMeter is better suited for our tests, when the open question (last bullet point) is solved. Gerbil is not suited because it cannot do the concurrent tests.

Without GERBIL we are unable to measure the quality of enrichments which is as important (IMO more important) as the performance. Getting familiar with JMeter is time-consuming since we don't have experience with the tool. Again, for concurrent tests we can write a bash-script and measure the speed.

**Comment by m1ci** [comment]
a very relevant comment on dataset for testing can be found here https://github.com/freme-project/freme-ner/issues/24#issuecomment-142633690

**Comment by pheyvaer** [comment]
@m1ci the question is does 'quality of enrichments' fall under 'load testing'? To me it doesn't ...

**Comment by m1ci** [comment]
> @m1ci the question is does 'quality of enrichments' fall under 'load testing'? To me it doesn't ...

Oh yes, you are right. But in the tests we would like to evaluate also the performance of FREME NER in terms of quality, so GERBIL is the right tool to do this. Unfortunately, concurrent requests are not supported by GERBIL, so for concurrent requests we need to use a script or tool such as JMeter.

**Comment by jnehring** [comment]
@m1ci wrote

> We can write simple bash script and measure this.

I think using a ready tool is better than writing a bash script most of the time. I suggest to watch [this 10 min video on JMeter](https://www.youtube.com/watch?v=8NLeq-QxkSw) for some superficial insight what JMeter is. It seems to be capable of exactly what we want to do. So no need to re-invent the wheel and write a bash script.

@m1ci wrote
> We have no experience with JMeter

I do not think that this is super hard to learn. And developers love to learn new technologies during their paid work time, am i right @xFran ?

@pheyvaer wrote
>the question is does 'quality of enrichments' fall under 'load testing'? To me it doesn't ..

Good point. In yesterdays developers call it sounded so nice to kill to sticks with one stone and get quality measurement and load testing at the same time. But actually I think that these are two different things and should not be confused with each other.

So I still think that JMeter is the better choice for load testing. Better then a bash script or Gerbil.

**Comment by jnehring** [comment]
We use a combination of JMeter python scripts.
