### ISSUE TITLE
Test setup for big data tests

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#65]
How do we do the setup for the big data tests?

I suggest to run them on freme-dev. Either we run them overnight or we send an email that nobody should be using FREME when the tests are performed in order to avoid noise in the tests.

There was also a discussion to do that on the Amazon cloud. I think this is very complicated and expensive.

**Comment by pheyvaer** [comment]
Can you control the network delay, latency, congestion, and so on of the clients when using the freme-dev?

**Comment by nilesh-c** [comment]
@jnehring at the moment freme-dev and freme-live are the same instance. We'll separate it soon and set freme-dev to the InfAI instance. That sounds like a good plan, to use freme-dev, but I would suggest doing the tests on the server itself to get rid of the network delay/latency variables. And I would also like to measure how increasing the number of akka threads, increasing Java Xmx for FREME NER and also for SOLR etc. impact performance.

**Comment by pheyvaer** [comment]
OK, but users will never access the server under ideal circumstances (no latency, delay, and so on), hence, to do representable test you should be able to have reproducible tests that replicate a typical user.

**Comment by m1ci** [comment]
Do we have info who is actively using freme at the moment? I think only wripl and AK prototyping - so I suggest we inform them in advance that we are going to do heavy test in a particular period.

Regarding the noise in the tests - maybe we allow access only for clients with specific IP - the one which will run the tests. This can be done with apache. What do you think?

> There was also a discussion to do that on the Amazon cloud. I think this is very complicated and expensive.

I share the same thoughts.

**Comment by jnehring** [comment]
@m1ci wrote
> Do we have info who is actively using freme at the moment? 

Unfortunately we dont have such analytics right now. And it will take some time until we integrate it. It is a good idea to implement a technical solution to block everyone else from using freme-dev. But when this is too complicated we can also send an email and kindly ask everyone not to use FREME at certain times.

@pheyvaer wrote

> to do representable test you should be able to have reproducible tests that replicate a typical user.

Typical user is hard to define. We can think of several load test scenarios

* One single user processing a large batch of data with FREME: This is what we want to test now. It is unrealistic because FREME will be used by multiple users. However it can give us first insights on the speed and processing powers of FREME.
* Many users doing concurrent requests. I am speaking of 100 parallel requests or similar numbers. We currently do not plan such tests. Here we also test for stability of FREME. However in future it is probable that we do such a test.

@nilesh-c  wrote

>  I would suggest doing the tests on the server itself to get rid of the network delay/latency variables.

That is a good idea. But right now we want to find out how WRIPL can tune their queue system to get the most out of FREME. To have most realistic numbers we should include the broker also. Your test is more in the direction of optimization of FREME NER. I think once we have the load tests for the broker we can easily adapt it for your needs.
