### ISSUE TITLE
Brainstorming on tutorials

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#66]
In the new homepage we will have a section about FREME tutorials.We should have a brain storming about which tutorials to write. We do not have to write all tutorials in FREME 0.4, when we have too many we will select a subset.

The tutorials should serve as documentation and also as a showcase what FREME is capable of. Please add your ideas for such a tutorial to this issue.

Here a first input:

* Do entity linking against “global airports” dataset to find airports in text documents
* Upload a custom dataset and perform entity linking against this dataset
* Use e-Translation to translate a document from Lithuanian to French
* Use e-Publishing to convert an HTML document into an EPUB3 file

**Comment by pheyvaer** [comment]
@jnehring In which format/template do you want the tutorials?

**Comment by jnehring** [comment]
@pheyvaer The new documentation homepage can be written either in HTML or in Markdown which will be compiled to HTML.

This issue is just about gathering ideas for these tutorials, we can write the tutorials in a 2nd step.

**Comment by xFran** [comment]
I don't know if this is off topic, but it will interesting to start think about SDK's for the most common programming languages used to build web applications and spend less time in making tutorials which you have to change for every release. I can see some benefits for both sides..

**Comment by jnehring** [comment]
> spend less time in making tutorials which you have to change for every release

Actually we dont plan to change the tutorials on every release. I hope that FREME is so stable that we dont have to change the documentation.

> it will interesting to start think about SDK's for the most common programming languages

Please create a new GitHub issue for this. In technical discussion forum. I think that software SDKs have nothing to do with the tutorials.
