### ISSUE TITLE
Check license for datasets

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#69]
Can we use Apache 2 license also for datasets? This issue prepares a discussion for the dev call and for our data management plan.

**Comment by m1ci** [comment]
I'm afraid we should apply the "underlying license" which is used for the raw data.
for cordis: http://ec.europa.eu/geninfo/legal_notices_en.htm
for dbpedia abstracts: CC-BY
for statbel: not sure, @fsalliau maybe can help here
for orcid: CC0 1.0 Public Domain Dedication as written here http://support.orcid.org/knowledgebase/articles/223698-how-do-i-get-a-public-data-file-
for global airports: Open Database License - as explained here http://openflights.org/data.html#license
> In short, these mean that you are welcome to use the data as you wish, if and only if you both acknowledge the source and and license any derived works made available to the public with a free license as well.
> Licenses for commercial use of data or derived images are available on request. Most simple cases, for example use of an image within a book or other printed publication, are granted for a flat fee of US$100. Please contact us for details.

I'm a bit puzzled. IMO it can be used for commercial purposes also only if we acknowledge and provide the data under a free public license - which we do.

**Comment by jnehring** [comment]
> In short, these mean that you are welcome to use the data as you wish, if and only if you both acknowledge the source and and license any derived works made available to the public with a free license as well.
Licenses for commercial use of data or derived images are available on request. Most simple cases, for example use of an image within a book or other printed publication, are granted for a flat fee of US$100. Please contact us for details.

That causes problems. Not for FREME but for business case partners using FREME.

**Comment by fsalliau** [comment]
I did some research on the website of Statbel, but terms of use are unclear to me. 
Don't put too much effort in this. Not even sure if Mediafin (the partner who was interested in this dataset) will remain on board.

**Comment by m1ci** [comment]
can we get some reasonable statement on the license of the statbel dataset? we need this for the deliverable.

**Comment by fsalliau** [comment]
Mediafin is no longer on board, there are currently no other parties interested in this dataset.
As far as I'm concerned, you don't need to invest more effort into this dataset.

**Comment by Nievesdfki** [comment]
Hello everybody, can someone of you confirm me that the statbel dataset is not going to be in used in FREME? also, are there any other datasets created that were not used or are not going to be used? thanks best

**Comment by fsalliau** [comment]
hi Nieves, i can confirm that for the time being (meaning until one of our BC partners shows interest) the statbel dataset is out of scope.

**Comment by fsasaki** [comment]
hi all, please keep the statbel dataset in the list of all datasets converted in FREME, including licenses aspects and usage aspects. This will be important for data management.

**Comment by m1ci** [comment]
in the DMP we need to indicate the license for the Statbel dataset. So far we dont have this info.

**Comment by fsalliau** [comment]
it's not clearly mentioned on the website, but i guess it's open data

**Comment by jnehring** [comment]
The DMP has been written so this issue is obsolete
