### ISSUE TITLE
Machine-read datahub.io

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#70]
Check if it is possible to machine read the fields from datahub in order to automatically create documentation and data management plan.

**Comment by jnehring** [comment]
datahub.io is a CKAN repository and therefore provides a CKAN API, see [Documentation](http://docs.ckan.org/en/ckan-2.0/#the-ckan-api).

This URL shows all datasets tagged with freme-project. `http://datahub.io/api/3/action/tag_show?id=freme-project`

So it is possible to machine read datahub.

**Comment by m1ci** [comment]
Discussed this with the principle maintainer of http://dataid.dbpedia.org/ and we came to following conclusion that generating dataID out of datahub.io description is not good way to go. Users use different properties to describe same info. So very often there will be miss match between datahub.io description and dataID.

We rather go the other way around - create dataID files for datasets using http://dataid.dbpedia.org/ and then push them to datahub.io. This is possible and can be done with the latest version of the dataID tooling. We can even update dataID descriptions and the push those updates to datahub.io - this is also feasible.

So, my suggestion will be to use dataID files as central point of documentation and use them to:
1) propagate those descriptions to datahub.io, and
2) automatically generate HTML documentation.

**Comment by jnehring** [comment]
> Users use different properties to describe same info.

There might be a misunderstanding. From my point of view we enter the information about our datasets in datahub ourselve so we can control the way we describe properties.

We need the metadata on Datahub, in the data management plan and on the documentation homepage. Adding an additional location for the metadata in RDF files located e.g. on GitHub sounds like a complicated solution to me. Also on Datahub we have a GUI to enter the data whereas in the RDF solution we have to edit RDF files by hand which is also more complicated. So I would still vote for Datahub as the central storage for dataset metadata.

**Comment by fsasaki** [comment]
+1.

2016-01-04 11:42 GMT+01:00 Jan Nehring <notifications@github.com>:

**Comment by jnehring** [comment]
The data management plan has been written so this issue is obsolete
