### ISSUE TITLE
Rename ConversionServices to FREMECommon

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#71]
@ghsnd has the issue that he needs the codes that manage users and their connection to the database codes in the pipelines repo. Right now the codes are integrated in the broker. I am sure that similar issues will come up in future.

They have to move out of the broker in order to be re-used in other repos, e.g. pipelines. But it is not a good idea to put them in the pipelines repo because they do not belong there. So my idea:

We rename ConversionServices to FREMECommon. Also the maven artifact will be renamed freme-common. Then we can put codes in that repo that are shared by FREME projects without belonging to one particular project. And we start with the user codes.

This requires us to change the dependency in all projects that use ConversionServices. But this is only a minor change.

**Comment by ghsnd** [comment]
Another option is (in the case of pipelines) to handle this user logic completely on the Broker. The standalone version would then just not have this functionality, or have another, maybe simpler, implementation of it. I think this might be feasible with Spring.

**Comment by jnehring** [comment]
@ghsnd I agree that your proposal is possible. In the case of the pipelines repo it means that there is a class describing a pipeline without user that is stored in the pipelines repo. And another class describing a pipeline with user in the broker repo. All the code to persist a pipeline will be stored in the brokers repo. I would prefer to have less codes in the broker. So lets move it all to FREMECommon.

In todays developer call we agreed on this procedure so I am going to implement it.

**Comment by ghsnd** [comment]
Great!

**Comment by m1ci** [comment]
> We rename ConversionServices to FREMECommon. Also the maven artifact will be renamed freme-common. Then we can put codes in that repo that are shared by FREME projects without belonging to one particular project. And we start with the user codes.

> This requires us to change the dependency in all projects that use ConversionServices. But this is only a minor change.

Makes sense. Good idea!

**Comment by jnehring** [comment]
* Changed ConversionServices pom.xml file to produce new artifact eu.freme.common:0.4-SNAPSHOT
* Changed Pipelines (@ghsnd please note the change) and Brokers pom.xml to include the new snapshot artifact. The other services include eu.freme.conversion:0.3 so we should change it only when necessary.
* Renamed Github repository
* Changed Jenkins configuration

**Comment by jnehring** [comment]
@ghsnd Some package names have changed. I updated pipelines master branch. You might want to merge the master branch in your CRUD development branch.
