### ISSUE TITLE
defining list of domains for e-Entity

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#72]
First step towards domain specific NER is having a list of domains.
We have several options:
1) use the TaaS classificaiton system: https://term.tilde.com/domains
2) use EuroVoc: http://eurovoc.europa.eu/drupal/?q=download/subject_oriented&cl=en (I think, TaaS is also based on EuroVoc but a bit polished)
3) define own domain classification

Pros and cons:
1) TaaS - pros: since it will be aligned with the e-Terminology, cons: has many domains - we can reuse only the top one
2) EuroVoc: pros: few clear domains, have localized names for the domains, cons: the domains might be too general
3) own domain classification: pros: from scratch we can define only relevant domains, no backward compatibility problems, cons: not adopted by the community, reinventing the wheel.

@koidl what do you think?
IMO re-using TaaS or EuroVoc is better then defining own. I suggest we re-use subset of TaaS, so at same time FREME NER will be aligned with the e-terminology domains so you can use FREME NER and e-Terminology in parallel.

**Comment by andish** [comment]
True, TaaS domain classification is based on EuroVoc. TaaS is aimed be more general and more-balanced to cover all subject fields. EuroVoc is more related to EU institutions and some domains are very widely described while some are missing.

**Comment by m1ci** [comment]
thanks for clarifying this, Andis. Can you share a link where we can download the TaaS in OWL or other machine readable format?

**Comment by andish** [comment]
We don't have it in RDF, it is in DB table. I can provide as CSV and then can generate  OWL.

**Comment by andish** [comment]
actually it is available via API as json or xml. Maube better than CSV

**Comment by m1ci** [comment]
can you share a link where I can get it in JSON?

**Comment by andish** [comment]
JSON
[TaaSDomains.txt](https://github.com/freme-project/technical-discussion/files/5985/TaaSDomains.txt)

**Comment by m1ci** [comment]
are all these domain in a same hierarchy level or there is tree structure?

**Comment by andish** [comment]
tree structure with 2 levels.
If parent is null, then it is a top level category.
````
{  
      "id":"TaaS-2304",
      "parent":"TaaS-2300",
      "name":"Dance"
   }
````
parent holds a reference to its parent entry.

Also ID shows if it is top level category like EuroVoc does. E.g the ID 'TaaS-2303' means that top category is TaaS-2300: first 2 numbers are for top category next 2 symbols for child category.

**Comment by m1ci** [comment]
clear now, thanks!

@koidl can you have a look at TaaS and check whether it is relevant for wripl. If yes, which domains are relevant, all, just subset? A prioritised list of domains is more than welcome.

**Comment by jnehring** [comment]
@m1ci @koidl I think we can close this issue?

**Comment by m1ci** [comment]
wripl is working on populating TaaS domains with DBpedia ontology types.
IMO we can close this issue.
