### ISSUE TITLE
Have datasets with resolvable URIs

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#76]
When we convert datasets to linked data then we should take care that the URIs are resolvable. This involves two tasks:

* Install Puppy (or a similar technology)
* Update the the URLs in the datasets to something like http://datasets.freme-project.eu/airports/id/1

We can schedule this feature for FREME 0.5

**Comment by m1ci** [comment]
makes sense, will consider this.

**Comment by m1ci** [comment]
resolvable URIs have been already configured. Example: http://data.freme-project.eu/resource/page/cordis/people/AdamMorawiecECSI

**Comment by m1ci** [comment]
We have resolvable URIs for the 
CORDIS FP7: http://data.freme-project.eu/resource/page/cordis/people/AdamMorawiecECSI
GRID: http://data.freme-project.eu/resource/page/grid/institutes/grid.414148.c and
Global Airports: http://data.freme-project.eu/resource/page/airports/1

**Comment by fsasaki** [comment]
Very cool, thanks!
I saw at
http://data.freme-project.eu/resource/page/cordis/people/AdamMorawiecECSI
that some generated triples hae URIs which not resolve, like
http://data.freme-project.eu/resource/page/cordis/organizations/EUROPEAN+ELECTRONIC+CHIPS+%26+SYSTEMS+DESIGN+INITIATIVE
Is this a technical issue or is the triple just with the wrong URI as object?

**Comment by m1ci** [comment]
it looks like technical issue due to the encodings in the URI. Let me investigate this.

**Comment by jnehring** [comment]
The three URIs 

CORDIS FP7: http://data.freme-project.eu/resource/page/cordis/people/AdamMorawiecECSI
GRID: http://data.freme-project.eu/resource/page/grid/institutes/grid.414148.c and
Global Airports: http://data.freme-project.eu/resource/page/airports/1

lead to

```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

I think the resolvable URIs are broken.

**Comment by m1ci** [comment]
fixed
