### ISSUE TITLE
Enhancement of e-Terminology to provide additional information related to terms?

### ISSUE THREAD

**Issue by fsasaki** [freme-project/technical-discussion#77]
e-Terminology creates URIs pointing to terminological linked about. E.g. having the input term “Schraubendreher” the e-Terminology output contains
http://tbx2rdf.lider-project.eu/data/iate/Schraubendreher-de.rdf

However, it seems that downloading above rdf file is just one step, other steps are needed for having really a useful application. E.g. one has to follow each ontolex:reference to find the IATE entry
http://tbx2rdf.lider-project.eu/data/iate/IATE-1813703

And then the subject field 44
http://tbx2rdf.lider-project.eu/data/iate/subjectField/44
“Employment and Working Conditions.”

It would be good if e-Terminology would provide access to the data sets that seem to be available in e-Terminology (like IATE) natively, without the need for the e-Terminology user to do additional queries themselves. A topic at the datathon could be: BC partners bring queries they want to make with e-Terminology and we discuss how to realise them or how to enhance e-Terminology itself.

**Comment by andish** [comment]
> e-Terminology (like IATE) natively, without the need for the e-Terminology user to do additional queries themselves

there is a possibility to get together with annotations also full terminology information. As all data is downloaded, needed data categories can be extracted in client side application.

if client will set annotation mode="spotting only" then will be returned just annotations not full terms.

**Comment by fsasaki** [comment]
"there is a possibility to get together with annotations also full terminology information. As all data is downloaded, needed data categories can be extracted in client side application."
About "As all data is downloaded": can you show a CURL request to e-Terminology that, with the input "Schraubendreher", downloads the data and that includes http://tbx2rdf.lider-project.eu/data/iate/subjectField/44
? I tried below but did not understand how to proceed.

curl -X POST --header "Content-Type: text/plain" --header "Accept: text/n3" "http://api.freme-project.eu/0.3/e-terminology/tilde?input=Schraubendreher&informat=text&outformat=turtle&source-lang=de&target-lang=en"

**Comment by andish** [comment]
Ok, I see. 
TBX2RDF convertor in e-Terminology has two issues to be resolved:
 * Namespace for lexicon is static and tied to IATE and lider project (IATE was converted with TBX2RDF conversion tool during LIDER project as showcase). It is just luck that URL is resolving http://tbx2rdf.lider-project.eu/data/iate/Schraubendreher-de.rdf (IATE also contains that term)
 * deal with subjectfields/domains - not included in conversion process, this was static content generated alongside the conversion of this tool

P.S. There should be no need to duplicate get and post parameters: informat vs Content-Type

**Comment by fsasaki** [comment]
Thanks for the item on duplication, makes sense. One question on this issue: at
https://term.tilde.com/lookup
I can look up translation suggestions, e.g. entering "Schraubendreher" gives me "screwdriver". So the Tilde terminology service has more data than being exposed via e-Terminology. Why is that the case?

**Comment by andish** [comment]
If search in returned result, there is "screwdriver":

```
<https://term.tilde.com/terms/screwdriver-en#CanonicalForm>
        ontolex:writtenRep  "screwdriver"@en .

:screwdriver-en  a             ontolex:LexicalEntry ;
        ontolex:canonicalForm  <https://term.tilde.com/terms/screwdriver-en#CanonicalForm> ;
        ontolex:language       <http://www.lexvo.org/page/iso639-3/eng> ;
        ontolex:sense          <https://term.tilde.com/terms/screwdriver-en#Sense> .
```

and information about domains should be added here:
```
:1156425  a           skos:Concept ;
        rdfs:comment  "Lenoch code: IN"@en , "Klavierbau"@en .
```

**Comment by fsasaki** [comment]
Thanks, I see that now. And I also get the translation to other languages, e.g. via 
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api.freme-project.eu/0.3/e-terminology/tilde?input=Schraubendreher&informat=text&outformat=turtle&source-lang=de&target-lang=lv"
What I don't understand yet: how to retrieve information about domains. If I go to 
https://term.tilde.com/terms/1156425
I get an HTML page via CURL. Is there a way to get this information in a machine readable manner?

**Comment by andish** [comment]
Unfortunately domain information is missing from the result of tbx2rdf conversion. We will look for solution. Created issues #79 and #80

**Comment by andish** [comment]
Issues #79 and #80 are resolved now

**Comment by jnehring** [comment]
@fsasaki @andish can we close this issue?

**Comment by fsasaki** [comment]
I don't know, @andish , is the below possible now?

About "As all data is downloaded": can you show a CURL request to e-Terminology that, with the input "Schraubendreher", downloads the data and that includes http://tbx2rdf.lider-project.eu/data/iate/subjectField/44
? I tried below but did not understand how to proceed.

curl -X POST --header "Content-Type: text/plain" --header "Accept: text/n3" "http://api.freme-project.eu/0.3/e-terminology/tilde?input=Schraubendreher&informat=text&outformat=turtle&source-lang=de&target-lang=en"

**Comment by andish** [comment]
```curl
curl -X POST --header "Content-Type: text/plain" --header "Accept: text/n3" "http://api-dev.freme-project.eu/current/e-terminology/tilde?input=Schraubendreher&informat=text&outformat=turtle&source-lang=de&target-lang=en&mode=full"
```

and the concept includes mapping to TaaS domain classification system:
```turtle
:1156425  a               skos:Concept ;
        rdfs:comment      "Lenoch code: IN"@en , "Klavierbau"@en ;
        tbx:definition    "Werkzeug zum Festziehen und Lösen von Schrauben mit einfach oder kreuzgeschlitztem Kopf."@en , "Meißelförmiges Werkzeug zum Festziehen und Lösen von Schrauben mit geschlitztem Kopf."@en , "A tool used for turning screws, usually having a handle of wood, plastic, etc., and a steel shank with a flattened square-cut tip that fits into a slot in the head of the screw."@en ;
        tbx:subjectField  <https://term.tilde.com/domains/TaaS-1500> , <https://term.tilde.com/domains/6846> .
```
Some concepts can contain also mappings to IATE, but all concept must contain mappings to TaaS clasification system.

**Comment by fsasaki** [comment]
thanks, @andish . So this issue can be closed.
