### ISSUE TITLE
human-readable URLs for datasets and endpoints

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#78]
We need to define persistent URLs for our datasets and the endpoints. The URLs (freme-project.eu domain) should exist and be valid also after the project ends.
Currently we have:
- Linked Data Fragment endpoint at http://rv2622.1blu.de:5000/ (freme-workers)
- Virtuoso SPARQL endpoint at http://rv2622.1blu.de:8890/sparql/
- dumps of the datasets at http://rv1460.1blu.de/datasets/ (freme-live)

My suggestion will be have:
- for Linked Data Fragments endpoint have http://fragments.freme-project.eu/ which will point to http://rv2622.1blu.de:5000/
- for SPARQL endpoint http://sparql.freme-project.eu/ and point to http://rv2622.1blu.de:8890/sparql/
- Datasets descriptions at http://www.freme-project.eu/datasets/{dataset-name}/ but dumps at http://datasets.freme-project.eu/{dataset-name}/ - this should point to http://rv1460.1blu.de/datasets/

Maybe something is not possible or better ideas pop up. Lets see.

**Comment by jnehring** [comment]
Thanks for moving that forward. How about having one subdomain http://data.freme-project.eu and then have URLs http://data.freme-project.eu/sparql/ , http://data.freme-project.eu/ldf/ and http://data.freme-project.eu/dumps/ . The idea is that we have less subdomains and therefore less configuration. Subdomains need to be configured by ISMB and therefore I think that only one subdomain is easier then three, and maybe more in future.

**Comment by m1ci** [comment]
yes, http://data.freme-project.eu/ is OK.
To which FREME server the http://data.freme-project.eu/ will point?

**Comment by jnehring** [comment]
I think we should point it to freme-worker. @m1ci  do you think it is a lot of work to move the dumps from freme-live to freme-worker? I guess it is only a matter of copying or do you need to update the documentation on datahub.io or something similar?

**Comment by m1ci** [comment]
> I think we should point it to freme-worker. @m1ci do you think it is a lot of work to move the dumps from freme-live to freme-worker?

It won't take much time to move them but I think its not good idea to use SSD for serving dumps. Why not serving them via freme-live or freme-dev?

**Comment by jnehring** [comment]
This is related to #76.

**Comment by m1ci** [comment]
closing this issue since it is related to https://github.com/freme-project/technical-discussion/issues/76

**Comment by m1ci** [comment]
btw, data.freme-project.eu points to frame-workers
