### ISSUE TITLE
e-Terminology - TBX2RDF conversion tool produces wrong namespace for lexicon

### ISSUE THREAD

**Issue by andish** [freme-project/technical-discussion#80]
Namespace for lexicon is static and tied to IATE and LIDER project (IATE was converted with TBX2RDF conversion tool during LIDER project as showcase). 
It is just luck that URL is resolving http://tbx2rdf.lider-project.eu/data/iate/Schraubendreher-de.rdf (IATE also contains that term)

**Comment by fsasaki** [comment]
Thanks a lot, @andis. Do you have a timeline for this? From my impression the discussion at the Leipzig hackathon could benefit a lot from having this feature. And the information seems to be available in the twaas service, see attached output. would it make sense to convert that output to RDF?
[taws-output-example.txt](https://github.com/freme-project/technical-discussion/files/13274/taws-output-example.txt)

**Comment by andish** [comment]
I hope this will be resolved soon, until 0.4 release. As tbx2rdf tool in Java, i have to set up dev environment for that and do some bugfixing.

**Comment by andish** [comment]
Resolved
