### ISSUE TITLE
Update list of 3rd party dependencies

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#81]

**Comment by ArneBinder** [comment]
Fixed bugs in MavenApacheLicenseUtil, enhanced usability and updated readme. Updated [the table](https://docs.google.com/spreadsheets/d/1j2XPwjRLTjyxFm0ceFf_Ts1tmigZEc-YatAWEaciz8k/edit#gid=397366127) with the information of the pom files, see the new FREME-0.4 sheet, but did not reviewed them yet and did not add additional license information. But there is the FREME version at the subproject/library position now, which eases the checkup.

**Comment by ArneBinder** [comment]
Updated the LICENSE-3RD-PARTY files for almost all FREME projects (except Documentation, epublib, eureka-services, sandbox). Opened [this](https://github.com/freme-project/Documentation/issues/103) concerning documentation.

@jnehring should we leave this open and recheck the 3rd party license table shortly before the next realise?

**Comment by ArneBinder** [comment]
Updated with current (2015-11-03) state.
