### ISSUE TITLE
License of Gerbil

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#82]
FREME NER uses Gerbil. The [Gerbil License](https://github.com/AKSW/gerbil/blob/master/LICENSE) says:

```
For non-commercial purposes, the terms of the LGPL3.0 license hold. These terms are available at http://www.gnu.org/licenses/lgpl-3.0.txt 
For commercial purposes, please contact the financial department of AKSW at jaenicke@uni-leipzig.de
```

@m1ci @nilesh-c Did you ask the financial department of AKSW? FREME is used commercially.

**Comment by jnehring** [comment]
Was discussed in [2015-11-26 call on FREME NER](https://docs.google.com/document/d/1KbWPOrLbz_B3UV9fyMj1LVuwQDHhdMcXGmSpF22JYio/edit?usp=drive_web)

**Comment by m1ci** [comment]
this issue is solved, no dependency to Gerbil anymore.
