### ISSUE TITLE
Adding NIF property its-annotators-ref to all e-Services

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#83]
In [another discussion](https://github.com/freme-project/e-Internationalization/issues/15) we found out that all NIF generated by FREME lacks the `its-annotators-ref` property which identifies the tool that produced the annotation.

So we should add this information to the NIF produced by each e-Service. In this issue we discuss how this information should look like. Then we can add this information to the e-Services e-entity, e-terminology and e-translation.

Also see http://www.w3.org/TR/its20/#its-tool-annotation

@m1ci added to the discussion

> the "its-annotators-ref" should be specified at the annotation level (<span>), and not "sentence" level. Reason: single content, can be processed by multiple e-Services and the result annotations and this might cause problems in decoding the provenance.

> in future we might include confidence scores not only for spotting, but also linking, classification, etc. This is still an open issue.

@m1ci can you post an example here? Do we add this information as a literal or do we identify the tool using a URI?

**Comment by m1ci** [comment]
Here is one example which adds the provenance information at the annotation level.

```
<html>
   <head>
   <body>
      <p>Welcome to <span its-annotators-ref="text-analysis|http://www.freme-project.eu/freme-ner" 
                                           its-ta-ident-ref="http://dbpedia.org/resource/Berlin"
                                           its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location"
                                           its-ta-confidence="0.7909971166830088">Berlin</span>, the capital of 
                                <span its-annotators-ref="text-analysis|http://www.freme-project.eu/freme-ner"
                                           its-ta-ident-ref="http://dbpedia.org/resource/Germany"
                                           its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location"
                                           its-ta-confidence="0.983524284693178">Germany</span>.</p>
   </body>
</html>
```

However, If the same HTML is processed by two services, say e-Entity and e-Terminology, and both services annotate same string, one as entity, one as term, and we want to encoded the results of both in the HTML using ITS - I'm not sure if this is possible. @fsasaki is it possible to have two annotations in HTML over same string? maybe having two spans - one wrapping another? :)

```
<span annotation-from-1-service><span annotation-from-2-service>Berlin</span></span>
```

**Comment by fsasaki** [comment]
Unfortunately that is not yet possible :( but maybe we should make it possible.

**Comment by jnehring** [comment]
Thanks @m1ci . How does the information look like in NIF?

**Comment by jnehring** [comment]
This issue is outdated because of the discussion on provenance in NIF.

**Comment by fsasaki** [comment]
There is a related issue: one needs to store in e-internationalization the annotators-ref information. But that is an e-internationalization issue. I'll open one.

**Comment by fsasaki** [comment]
Actually, there is an open one already:
https://github.com/freme-project/e-Internationalization/issues/32
