### ISSUE TITLE
Evaluate new relic

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#84]
Please register at www.newrelic.de and try out the http monitoring.

* Find out pricing. What can we do with a free account? Is it possible to get a free account as a research project? Paste the links here.
* Play around with http monitoring of
    * FREME APIs (live api, dev api)
    * DBPedia Spotlight
    * Tilde MT
    * Tilde Terminology
    * SPARQL / LDF endpoints of the FREME templates
    * FREME SPARQL endpoint
    * FREME LDF endpoint

The purpose of HTTP monitoring is

* Find out the uptime of FREME live
* When freme-live is down we immediately get a notification email

**Comment by ArneBinder** [comment]
Feature list for the different pricing models: [see here](http://www.newrelic.de/application-monitoring/pricing)

**Comment by ArneBinder** [comment]
tutorial [Including Java Agent in Standalone Spring Boot Application ](https://dzone.com/articles/including-java-agent)

**Comment by jnehring** [comment]
We will not use Zabbix because the free version is not powerful enough in regards of HTTP monitoring

**Comment by ArneBinder** [comment]
Is the newrelic javaagent already disabled? (removing additional VM parameters from broker: -javaagent:/path/to/newrelic/newrelic.jar -Dnewrelic.environment=development)
