### ISSUE TITLE
Evaluate Zabbix

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#85]
For HTTP monitoring

Play around with http monitoring of
* FREME APIs (live api, dev api)
* DBPedia Spotlight
* Tilde MT
* Tilde Terminology
* SPARQL / LDF endpoints of the FREME templates
* FREME SPARQL endpoint
* FREME LDF endpoint

The purpose of HTTP monitoring is

* Find out the uptime of FREME live
* When freme-live is down we immediately get a notification email

**Comment by ArneBinder** [comment]
tutorial: http://lab4.org/wiki/Zabbix_Schnellstart

**Comment by jnehring** [comment]
Next steps

* Do ping test with a test.html page
* Setup email notifications using a freemail account (e.g. Google Mail). We do not want to install an email server on freme-dev
* Find a way to measure uptime
* Check how to put the most important information in the dashboard

**Comment by jnehring** [comment]
Next steps

* Switch off monitoring for api-dev
* Failed e-Service test: Severity high. Failed external service test: Average
* Add tests for Tilde APIs. Check broker repository to see how to create an API request for Tilde
* Remove group "Sparql Endpoint"
* Add tests for SPARQL endpoints. Check availabilty of endpoint URL (e.g. http://dbpedia.org/sparql) without query. Monitor all SPARQL endpoints from http://api-dev.freme-project.eu/doc/api-doc/list-templates.html
* Check out the "reports" feature

Unclear

* We should have a documentation how to use Zabbix and where to find the most important information, e.g. the Uptime / SLA. We need to define the important information. The documentation should also link to the official Zabbix documentation.

**Comment by ArneBinder** [comment]
>Add tests for Tilde APIs. Check broker repository to see how to create an API request for Tilde

It's not possible to monitor (via a web scenario) the Tilde Translation service via POST, because zabbix does not provide the possibility to send a body and Tilde services expect a not empty body. The same holds for the Tilde Terminology service. At the moment, the GET version is used for monitoring Tilde services assuming that POST will also fail, if GET fails.

**Comment by ArneBinder** [comment]
**Next Steps:**
1) please figure out, where to put zabbix documentation
2) documentation (@jnehring: please add missing items)
  * simplified monitoring workflow/structure (current templates, etc.)
  * "shortcuts" to important informations:
    * SLA
  * how-to add notification email
2) monitor system properties of FREME live
  * CPU
  * memory
  * HD access

**Comment by jnehring** [comment]
I created a folder [internal documentation](https://drive.google.com/drive/folders/0B8CeKhHCOSqUWWs0OHFBeldHWFk) in the GoogleDrive. Please create a new document and put the documentation there.

About the documentation: These are good points you wrote. I still need some more explanation how the Zabbix system works and on what it offers. Next week we should talk and then I am sure I will ask for some more "shortcuts".

> 3) monitor system properties of FREME live

Please monitor freme-dev first and not freme-live.

**Comment by jnehring** [comment]
Please write documentation as you specified it.
Do not invest any time in 3) monitoring of system properties.

**Comment by ArneBinder** [comment]
I've created some docu. @jnehring could you have a look?

**Comment by jnehring** [comment]
Nice docu, thanks.

I stored the credentials in a keystore. Please dont put it in the documentation.
