### ISSUE TITLE
More input / output formats for e-Internationalization

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#94]
Thinking about the feature set for FREME 0.5 and new input / output formats for e-Internationalization: Are there any "low hanging fruits" we can get using Okapi? I guess that especially conversion from an format to NIF can be easily implemented using Okapi for a lot more formats. @borriellom can you make some suggestions for formats we can easily cover?

Some suggestions (wishlist):
- Microsoft office formats like .doc, .docx
- MP3 (extract textual metadata)

**Comment by fsasaki** [comment]
could we keep this open, just so that we don't forget about the format
issue? or have it as a topif of 0.6 features again?

2016-02-10 16:28 GMT+01:00 Jan Nehring <notifications@github.com>:

**Comment by jnehring** [comment]
I open it and put it on the specification of FREME 0.6.

**Comment by jnehring** [comment]
i guess that this will not be implemented during the freme project.
