### ISSUE TITLE
Convert Grid dataset to LD

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#96]
http://www.grid.ac/

Some information on how to create linked data:

[Linking the Apertium Bilingual Dictionaries on the Web of Data](https://drive.google.com/open?id=0B8CeKhHCOSqUQW0xVzVIREFMMUE)

[Linked Data: Evolving the Web into a Global Data Space](http://linkeddatabook.com/editions/1.0/), [Especially this chapter](http://linkeddatabook.com/editions/1.0/#htoc61)

**Comment by m1ci** [comment]
done by INFAI
