### ISSUE TITLE
Evaluate Apache JMeter

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#97]
Play around with [Apache JMeter](http://jmeter.apache.org/).

1) Generate a set test set of 10 wikipedia articles as .txt files
2) Try Apache JMeter and send the 10 wikipedia articles through FREME NER
3) First use the GUI
4) Check if the tool can be used without GUI from a unit test

Related issues: #64, #65, https://github.com/freme-project/freme-ner/issues/24

**Comment by jnehring** [comment]
1,2,3, 4 solved. The tool looks promising and can also be called from Java code without GUI for a unit test.

Next steps:

* Find dataset for performance analysis (freme-project/freme-ner#24)
* run tests on this dataset
* calculate
    * average / min / max response time
    * Std Deviation
    * Throughput
* Play around with number of threads parameter to find the optimal number of threads to consume FREME. We need the possibility to repeat this task in future.

**Comment by josauder** [comment]
Worked on this, can be found [here](https://github.com/josauder/loadtest/).

**Comment by jnehring** [comment]
Thanks. Next steps

* Move the code to https://github.com/freme-project/load-testing
* Instead of average / min / max response time please measure the time you need in total to process the dataset

We should find a way to disable the Solr Cache for the unit tests.
