### ISSUE TITLE
Specify batch processing tool

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#99]
We should create a tool so users can process batches of data with FREME. A first brainstorming on the feature set:

* This is a command line tool writtin in Java
* Runs on the client side
* Use a configuration file that uses the same syntax like the pipelines module to specify how FREME API is called
* Crawl a directory with many files and process all files via FREME. It creates proper URIs. The first version should send plaintext to FREME, future versions should also support NIF input.
* Store the results of enrichment somehow. I think it should write the output either to the console or to a file. For the first version a single output format like n-triples is enough.
* Configurable number of threads to specify the degree of parallelism.

**Comment by ghsnd** [comment]
> Configurable number of threads to specify the degree of parallelism.

An important thing here is to consider the rate limits...

**Comment by jnehring** [comment]
> An important thing here is to consider the rate limits...

Yes. The tool should take a break when a rate limit is reached.

**Comment by fsalliau** [comment]
@jnehring @ghsnd please take into account planning for this.
when is 0.5 due?

**Comment by jnehring** [comment]
> when is 0.5 due?

end of implementation: January 20th 2016
end of bugfixing: February 3rd 2016
release: February 5th 2016

**Comment by fsalliau** [comment]
we'll discuss in Athens whether it is feasible to have a first version of the plugin ready by end of January (for the FREME Alpha deliverable).
If so, this task might be necessary to postpone to the next release.

**Comment by jnehring** [comment]
Actually this task is just about specifying the tool. I think that we have to carefully plan the feature set in order to make it useful. E.g. above point of creating URIs doesnt seem to be very easy to me. It also involves talks to WRIPL and to Agro-Know how they use the tool. So you have time for this task until 5th of february.

We can implement it in FREME 0.6.

**Comment by ghsnd** [comment]
The draft: https://goo.gl/i4vXZv

**Comment by ghsnd** [comment]
A first version of the Batch Processing Tool Specification is ready. In the `freme-project/Development/Batch Processing Tool` folder on Google Drive, there are 2 documents now:
* **Batch Processing Tool Specification (working draft)**: this document that will serve as a basis for future releases. Feel free to comment or edit this at any time.
* **Batch Processing Tool Specification (V1.0 20160205)**: the specification for this release. At this moment it is a copy of the working draft. Please do not edit after the 0.5 release.
